kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-storage
  labels:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
