apiVersion: dataservices.nutanix.com/v1alpha1
kind: ProtectionPlan
metadata: 
  annotations:
    argocd.argoproj.io/sync-wave: "10"
 name: pacman-protectionplan
spec: 
 scheduleName: minute-interval
 retentionPolicy:
     retentionCount: 3
 replicationConfigs:
   - replicationTargetName: remote-pacman